version: "3.7"
services:
  app:
    image: ghcr.io/${GITHUB_ACTOR}/${PROJECT_NAME}:latest
    container_name: fastapi
    ports:
      - "33333:33333"
    env_file:
      - .env
    networks:
      - app

networks:
  app:
    external: true
